server/db/models/index.js
server/db/models/product.js
server/db/models/user.js

Models rachel

---

server/db/models/product.js
server/db/models/user.js

Updated User and Product model 
---

added hooks and more allownulls

---

server/db/models/user.js

removed user hook

---

server/api/index.js
server/api/products.js
server/api/users.js
server/db/models/user.js

started routes

---

script/seed.js
server/db/models/product.js

fixed db bugs

---

server/api/users.spec.js

changed last spec

---

server/api/products.js
server/api/users.js

User routes

---

server/api/users.spec.js

just commented specs out

---

client/components/navbar.js
client/routes.js

fixed guest access to products

---

client/components/Item.js
client/components/SingleProduct.js
client/components/navbar.js
public/index.html
script/seed.js
server/db/models/product.js

update: products vertical slice & seed

---

server/db/index.js
server/db/models/orders.js
server/db/models/productOrders.js

Order model

---

client/components/Item.js
client/components/navbar.js
server/auth/index.js
server/db/models/orders.js

Minor updates products

---

client/components/LoginPage.js
client/components/auth-form.js
client/routes.js

Seperate login

---

client/components/Item.js
client/components/UserAccount.js
client/store/cart.js
server/auth/index.js

Buybutton useracct

---

client/routes.js
server/api/orders.js
server/db/models/orders.js
server/db/models/user.js

… back to boilermaker way of logging in and signing up, also wrote the orders routes for the cart

feature and fix, changed allowNulls in model and did orders routes

---

client/components/UserAccount.js
client/components/auth-form.js
client/components/navbar.js
client/routes.js
server/auth/index.js

fix login and signup

---

client/components/AllProducts.js
client/components/Item.js
client/components/ItemForm.js

Hid update form and buttons from non-Admins

Admin stuff again

---

client/components/AllUsers.js
client/store/user.js

feat-allUsers component

---

client/components/Item.js
client/store/cart.js
server/api/orders.js
server/db/models/orders.js
server/db/models/productOrders.js

feature: playing around with Redux store for the shopping cart

---

server/api/orders.js

finally fixed the route for getting someone's cart

---

client/components/Added.js
client/components/Item.js
client/components/ItemForm.js
client/store/cart.js
client/store/product.js
server/api/orders.js

idk a bunch of little things

---

client/components/AddProduct.js
client/components/AllProducts.js
client/store/product.js
server/api/products.js

added: form on all products page for logged-in admins to add products

added: form for admins to add products

---

client/components/user-home.js
client/components/user-home.spec.js
client/product.spec.js
server/db/models/models.spec.js

wrote a few more tests to get us to twenty

---

client/components/Added.js
client/components/Item.js
client/components/Viewcart.js
client/components/user-home.js
client/store/cart.js
server/api/orders.js
server/db/models/orders.js
server/db/models/productOrders.js

some updates to viewing carts, etc.

---

client/components/Item.js
client/store/cart.js
server/api/orders.js
server/db/models/orders.js
server/db/models/productOrders.js

quantity works but price never does, so i'm taking a break, lol

---

client/components/Checkout.js
client/components/Viewcart.js
client/routes.js
public/style.css

halfway through checkout page

---

client/components/user-home.js
client/store/user.js

just the casing issue

---

client/components/AddProduct.js
client/components/ItemForm.js
server/auth/index.js

- fixed cart for newly signed-up users
- added front-end form validations (well it just can't be empty now at least)
- did nothing regarding checkout so this branch name is irrelevant lol

Checkin checkout

---

client/components/LoginPage.js
client/store/user.js

logout issue fixed

---

client/components/navbar.js

admin link no longer appears for non admin

---

client/components/Checkout.js
client/components/Viewcart.js
client/store/cart.js
server/db/models/orders.js
server/db/models/user.js

started checkout form

---

script/seed.js

changed seed

---

client/components/AddProduct.js
client/components/Item.js
client/components/Viewcart.js
public/style.css

replaced input field with a dropdown box to select qty

---

client/components/Viewcart.js
client/store/cart.js
server/api/orders.js

made edits to get checkout working, we shall see

---

server/db/models/orders.js

price and quantity should be working now

---

client/components/Viewcart.js
client/store/cart.js
server/api/orders.js

viewcartFix

---

client/components/Checkout.js

removedorderdetail

---

client/components/Checkout.js
server/api/orders.js

trying checkout stuff

---

client/components/Viewcart.js

viewcart is hopefully working now
